services:
  postgres:
    image: postgres:16-alpine
    container_name: erp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: erp
    ports:
      - "5432:5432"
    volumes:
      - erp_pg:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: erp_redis
    ports:
      - "6379:6379"

volumes:
  erp_pg: